### ISSUE TITLE
False positive in `check-redirects`

### ISSUE THREAD

**Issue by TicClick** [cl8n/osu-wiki-bin#9]
found in https://github.com/ppy/osu-wiki/pull/9900 -- the below redirects work as intended on the website:
- https://osu.ppy.sh/wiki/people/the_team/nomination_assessment_team
- https://osu.ppy.sh/wiki/people/the_team

tool output:
```
Redirect "people/the_team/nomination_assessment_team" is shadowed by an existing article and has no effect
Redirect "people/the_team" is shadowed by an existing article and has no effect
```

`redirect.yaml`: https://github.com/ppy/osu-wiki/blob/85675aaaf954b7cebc48d7ddfee6206cd7e16d37/wiki/redirect.yaml#L2073

(inb4: no, I don't have `people/the_team` locally, not even an empty folder, and if it was due to https://github.com/ppy/osu-wiki/blob/85675aaaf954b7cebc48d7ddfee6206cd7e16d37/wiki/redirect.yaml#L2095C2-L2095C17, it would fail other redirects with the `people/the_team` prefix)

**Comment by cl8n** [comment]
> inb4: no, I don't have `people/the_team` locally

all I can really say is "are you sure" cuz it's the only way I can see that this message would come up lol. i dont get this error on master

for sanity can u try this in a clean clone of osu-wiki?

**Comment by TicClick** [comment]
took a second look, and there was a typo in my `stat` command... yes, I had an empty directory for some reason (the NAT one specifically, of all groups)
